(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d',{alpha:false});
const UI={hud:$('hud'),score:$('scoreValue'),runCoins:$('runCoins'),toast:$('landingToast'),start:$('startScreen'),over:$('gameOverScreen'),best:$('bestScore'),total:$('totalCoins'),play:$('playButton'),retry:$('retryButton'),menu:$('menuButton'),title:$('gameOverTitle'),reason:$('gameOverReason'),final:$('finalScore'),finalBest:$('finalBest'),finalCoins:$('finalCoins'),pause:$('pauseButton'),pauseOverlay:$('pauseOverlay'),resume:$('resumeButton')};
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t,smooth=t=>t*t*(3-2*t);
const saveKey='driftline-save-v4';let save={best:0,coins:0};try{save={...save,...JSON.parse(localStorage.getItem(saveKey)||'{}')}}catch{}const persist=()=>localStorage.setItem(saveKey,JSON.stringify(save));
let W=1,H=1,D=1;function resize(){W=innerWidth;H=innerHeight;D=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(W*D);canvas.height=Math.round(H*D);canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize,{passive:true});resize();
const images={};for(const [k,src] of Object.entries({ball:'assets/ball.svg',coin:'assets/coin.svg',bg:'assets/background.svg'})){const im=new Image;im.src=src;images[k]=im}
class Sfx{unlock(){if(this.c)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;this.c=new A;this.g=this.c.createGain();this.g.gain.value=.14;this.g.connect(this.c.destination)}tone(a,b,d=.08,t='sine'){this.unlock();if(!this.c)return;const n=this.c.currentTime,o=this.c.createOscillator(),g=this.c.createGain();o.type=t;o.frequency.setValueAtTime(a,n);o.frequency.exponentialRampToValueAtTime(Math.max(40,b),n+d);g.gain.setValueAtTime(.001,n);g.gain.exponentialRampToValueAtTime(.12,n+.01);g.gain.exponentialRampToValueAtTime(.001,n+d);o.connect(g);g.connect(this.g);o.start(n);o.stop(n+d+.02)}}const sfx=new Sfx;
function introGround(px){const pts=[[0,.34],[170,.31],[520,.82],[850,.47],[1120,.72],[1350,.58]];for(let i=0;i<pts.length-1;i++){const [x0,y0]=pts[i],[x1,y1]=pts[i+1];if(px<=x1){const t=smooth(clamp((px-x0)/(x1-x0),0,1));return H*lerp(y0,y1,t)}}return H*.58}
function endlessGround(px){const q=clamp((px-1200)/18000,0,1);return H*.66+Math.sin(px/330)*(56+25*q)+Math.sin(px/155+1.1)*(21+15*q)+Math.sin(px/74+.4)*(5+4*q)}
function ground(px){if(px<1250)return introGround(px);if(px<1500){const t=smooth((px-1250)/250);return lerp(introGround(px),endlessGround(px),t)}return endlessGround(px)}
function slope(px){const e=1.5;return(ground(px+e)-ground(px-e))/(e*2)}
class Coins{constructor(){this.a=[];this.next=700}reset(){this.a=[];this.next=700;this.ensure(2600)}ensure(to){while(this.next<to){const s=this.next,n=6+Math.floor((s/800)%4),sp=39,h=72+24*Math.sin(s/410);for(let i=0;i<n;i++){const u=i/(n-1),px=s+i*sp;this.a.push({x:px,y:ground(px)-50-Math.sin(Math.PI*u)*h,got:false,p:Math.random()*TAU})}this.next+=n*sp+260}}}
class Particles{constructor(){this.a=[]}clear(){this.a=[]}burst(x,y,c,n=10,s=130){for(let i=0;i<n;i++){const a=Math.random()*TAU,v=s*(.5+Math.random()*.7);this.a.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,l:.5,m:.5,r:2+Math.random()*3,c})}}update(dt){for(let i=this.a.length-1;i>=0;i--){const p=this.a[i];p.l-=dt;if(p.l<=0){this.a.splice(i,1);continue}p.vy+=260*dt;p.x+=p.vx*dt;p.y+=p.vy*dt}}}
const coins=new Coins,parts=new Particles;
const G={state:'menu',held:false,score:0,runCoins:0,cam:0,shake:0,toast:0,stall:0,last:performance.now(),acc:0,step:1/120,p:{x:120,y:0,vx:300,vy:0,r:20,vr:23,on:true,rot:0,air:0}};
function screens(s){UI.start.classList.toggle('active',s==='menu');UI.over.classList.toggle('active',s==='gameover');UI.hud.classList.toggle('active',s==='playing'||s==='paused');UI.pause.style.display=s==='playing'?'block':'none';if(s!=='paused'){UI.pauseOverlay.classList.remove('active');UI.pauseOverlay.setAttribute('aria-hidden','true')}}
function menuStats(){UI.best.textContent=Math.floor(save.best)+' m';UI.total.textContent=save.coins}
function reset(){const p=G.p;p.x=120;p.y=ground(p.x)-p.r;p.vx=300;p.vy=slope(p.x)*p.vx;p.on=true;p.rot=0;p.air=0;Object.assign(G,{score:0,runCoins:0,cam:0,shake:0,toast:0,stall:0,held:false,acc:0});coins.reset();parts.clear();UI.score.textContent='0 m';UI.runCoins.textContent='0';UI.toast.classList.remove('show')}
function start(){sfx.unlock();sfx.tone(500,720,.06,'triangle');reset();G.state='playing';screens('playing')}
function showMenu(){G.state='menu';G.held=false;screens('menu');menuStats()}
function fail(t,r){if(G.state!=='playing')return;G.state='gameover';G.held=false;G.shake=10;parts.burst(G.p.x,G.p.y,'#ff5c62',18,180);sfx.tone(120,55,.22,'sawtooth');const d=Math.floor(G.score);save.best=Math.max(save.best,d);save.coins+=G.runCoins;persist();UI.title.textContent=t;UI.reason.textContent=r;UI.final.textContent=d+' m';UI.finalBest.textContent=Math.floor(save.best)+' m';UI.finalCoins.textContent=G.runCoins;setTimeout(()=>screens('gameover'),180)}
function toast(t,c='#fff'){UI.toast.textContent=t;UI.toast.style.color=c;UI.toast.classList.add('show');G.toast=.65}
function pause(){if(G.state!=='playing')return;G.state='paused';G.held=false;UI.pauseOverlay.classList.add('active');UI.pauseOverlay.setAttribute('aria-hidden','false');screens('paused')}
function resume(){if(G.state!=='paused')return;G.state='playing';G.last=performance.now();screens('playing')}
function collect(){const p=G.p;coins.ensure(p.x+W*2);for(const q of coins.a){if(q.got)continue;const dx=q.x-p.x;if(dx<-80)continue;if(dx>100)break;const dy=q.y-p.y;if(dx*dx+dy*dy<32*32){q.got=true;G.runCoins++;UI.runCoins.textContent=G.runCoins;parts.burst(q.x,q.y,'#ffd33d',9,110);sfx.tone(850,1250,.08)}}}
function land(a,sp,impact){const p=G.p,v=Math.atan2(p.vy,p.vx);let d=Math.abs(v-a);while(d>Math.PI)d-=TAU;d=Math.abs(d);if(impact>430||d>.72){fail('Hard landing','Match the slope before touching down.');return false}if(d<.2&&impact<280){p.vx=Math.max(250,sp*1.08);toast('PERFECT','#fff5a8');parts.burst(p.x,p.y+p.r,'#fff',12,100);sfx.tone(520,820,.12,'triangle')}else{p.vx=Math.max(220,sp*.96);toast('GOOD');sfx.tone(360,500,.08,'triangle')}return true}
function update(dt){const p=G.p;if(p.on){const s=slope(p.x),a=Math.atan2(s,1),tx=Math.cos(a),ty=Math.sin(a);let sp=Math.hypot(p.vx,p.vy);sp+=(1050*ty+(G.held?Math.max(0,ty)*560:0)-(8+sp*.002))*dt;const launch=!G.held&&s<-.1&&sp>220,crest=s<-.06&&slope(p.x+20)>s+.1;p.vx=tx*sp;p.vy=ty*sp;p.x+=p.vx*dt;p.y=ground(p.x)-p.r;p.rot+=sp/p.r*dt;if((launch||crest)&&ground(p.x+10)-p.r>p.y+p.vy*dt+1){p.on=false;p.air=0;p.vy-=launch?55:24;sfx.tone(220,430,.1,'triangle')}if(p.x>1450&&s<-.08&&sp<82)G.stall+=dt;else G.stall=Math.max(0,G.stall-dt*2);if(p.vx<=0||sp<2){fail('Momentum lost','Carry more speed into the climb.');return}if(G.stall>.2){fail('Stalled','Dive deeper before the next climb.');return}}else{p.air+=dt;p.vy+=(G.held?1260:760)*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.rot+=p.vx/p.r*dt;const gy=ground(p.x)-p.r;if(p.y>=gy){const a=Math.atan2(slope(p.x),1),tx=Math.cos(a),ty=Math.sin(a),sp=Math.max(0,p.vx*tx+p.vy*ty),impact=Math.abs(-p.vx*ty+p.vy*tx);p.y=gy;p.on=true;if(!land(a,sp,impact))return;p.vy=slope(p.x)*p.vx;p.air=0}if(p.vx<=0){fail('Moving backward','Keep forward momentum at all times.');return}}collect();G.score=Math.max(G.score,(p.x-120)/10);UI.score.textContent=Math.floor(G.score)+' m';G.cam=lerp(G.cam,p.x-W*.27,1-Math.pow(.001,dt));if(G.toast>0&&(G.toast-=dt)<=0)UI.toast.classList.remove('show');parts.update(dt)}
function drawBackground(){if(images.bg.complete&&images.bg.naturalWidth){const h=H,w=h*2.9,off=-((G.cam*.08)%w);for(let x=off-w;x<W+w;x+=w)ctx.drawImage(images.bg,x,0,w,h)}else{const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#08c8cb');g.addColorStop(1,'#d9f4c7');ctx.fillStyle=g;ctx.fillRect(0,0,W,H)}}
function drawTerrain(){ctx.beginPath();ctx.moveTo(0,H+30);for(let sx=-8;sx<=W+8;sx+=8)ctx.lineTo(sx,ground(G.cam+sx));ctx.lineTo(W+8,H+30);ctx.closePath();const g=ctx.createLinearGradient(0,H*.45,0,H);g.addColorStop(0,'rgba(56,190,180,.9)');g.addColorStop(1,'#168f95');ctx.fillStyle=g;ctx.fill();ctx.beginPath();for(let sx=-8;sx<=W+8;sx+=8){const y=ground(G.cam+sx);sx===-8?ctx.moveTo(sx,y):ctx.lineTo(sx,y)}ctx.strokeStyle='rgba(220,255,245,.72)';ctx.lineWidth=4;ctx.stroke()}
function drawCoins(){const t=performance.now()*.004;for(const q of coins.a){if(q.got)continue;const sx=q.x-G.cam;if(sx<-40||sx>W+40)continue;const y=q.y+Math.sin(t+q.p)*2.5,sz=29;if(images.coin.complete&&images.coin.naturalWidth)ctx.drawImage(images.coin,sx-sz,y-sz,sz*2,sz*2);else{ctx.fillStyle='#ffd33d';ctx.beginPath();ctx.arc(sx,y,12,0,TAU);ctx.fill()}}}
function drawParts(){for(const p of parts.a){ctx.globalAlpha=clamp(p.l/p.m,0,1);ctx.fillStyle=p.c;ctx.beginPath();ctx.arc(p.x-G.cam,p.y,p.r,0,TAU);ctx.fill()}ctx.globalAlpha=1}
function drawBall(){const p=G.p,sx=p.x-G.cam,sz=p.vr*2;ctx.save();ctx.translate(sx,p.y);ctx.rotate(p.rot);ctx.shadowColor='rgba(0,80,90,.28)';ctx.shadowBlur=12;if(images.ball.complete&&images.ball.naturalWidth)ctx.drawImage(images.ball,-sz/2,-sz/2,sz,sz);else{ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(0,0,p.r,0,TAU);ctx.fill()}ctx.restore()}
function draw(){drawBackground();const sx=G.shake?(Math.random()-.5)*G.shake:0,sy=G.shake?(Math.random()-.5)*G.shake:0;G.shake*=.88;ctx.save();ctx.translate(sx,sy);drawTerrain();drawCoins();drawParts();drawBall();ctx.restore()}
function loop(n){const dt=Math.min(.05,Math.max(0,(n-G.last)/1000));G.last=n;if(G.state==='playing'){G.acc+=dt;while(G.acc>=G.step){update(G.step);G.acc-=G.step;if(G.state!=='playing')break}}else parts.update(dt);draw();requestAnimationFrame(loop)}
const down=e=>{if(G.state==='playing'){G.held=true;sfx.unlock();e.preventDefault()}},up=e=>{G.held=false;e?.preventDefault?.()};canvas.addEventListener('pointerdown',down,{passive:false});addEventListener('pointerup',up,{passive:false});addEventListener('pointercancel',up,{passive:false});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();if(G.state==='menu'||G.state==='gameover')start();else if(G.state==='playing')G.held=true}if(e.code==='Escape'){G.state==='playing'?pause():G.state==='paused'&&resume()}});addEventListener('keyup',e=>{if(e.code==='Space')G.held=false});
UI.play.addEventListener('click',start);UI.retry.addEventListener('click',start);UI.menu.addEventListener('click',showMenu);UI.pause.addEventListener('click',pause);UI.resume.addEventListener('click',resume);menuStats();reset();screens('menu');requestAnimationFrame(n=>{G.last=n;requestAnimationFrame(loop)});
})();